export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_DONE = 'CHECK_LOGIN_DONE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_DONE = 'LOGOUT_DONE';

// ---------- USERS
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAILED = 'BLOCK_USER_FAILED';

// ---------- CATEGORY
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_CATEGORY_SUCCESS = 'SELECT_CATEGORY_SUCCESS';
export const SELECT_CATEGORY_FAILED = 'SELECT_CATEGORY_FAILED';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

// ---------- PRODUCT
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_PRODUCT_SUCCESS = 'SELECT_PRODUCT_SUCCESS';
export const SELECT_PRODUCT_FAILED = 'SELECT_PRODUCT_FAILED';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

export const SUGGEST_SEARCH_PRODUCT = 'SUGGEST_SEARCH_PRODUCT';
export const SUGGEST_SEARCH_PRODUCT_SUCCESS = 'SUGGEST_SEARCH_PRODUCT_SUCCESS';
export const SUGGEST_SEARCH_PRODUCT_FAILED = 'SUGGEST_SEARCH_PRODUCT_FAILED';

export const SUBMIT_PRODUCT_SUGGEST = 'SUBMIT_PRODUCT_SUGGEST';
export const CLEAR_PRODUCT_SUGGEST = 'CLEAR_PRODUCT_SUGGEST';

// ---------- ORDERS
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILED = 'GET_TRANSACTIONS_FAILED';

export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';
export const SELECT_TRANSACTION_SUCCESS = 'SELECT_TRANSACTION_SUCCESS';
export const SELECT_TRANSACTION_FAILED = 'SELECT_TRANSACTION_FAILED';

export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAILED = 'UPDATE_TRANSACTION_FAILED';

// ---------- BUDGET
export const GET_BUDGET = 'GET_BUDGET';
export const GET_BUDGET_SUCCESS = 'GET_BUDGET_SUCCESS';
export const GET_BUDGET_FAILED = 'GET_BUDGET_FAILED';

export const GET_YEARBUDGET = 'GET_YEARBUDGET';
export const GET_YEARBUDGET_SUCCESS = 'GET_YEARBUDGET_SUCCESS';
export const GET_YEARBUDGET_FAILED = 'GET_YEARBUDGET_FAILED';